name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/Shaquille-design/WindowsRDP/main/nssm.exe
        Invoke-WebRequest https://raw.githubusercontent.com/Shaquille-design/WindowsRDP/main/ngrok.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Users\ASUS\Documents\RDP
        copy ngrok.exe C:\Users\ASUS\Documents\RDP
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://github.com/Shaquille-design/WindowsRDP/blob/main/NGROK-AP.bat
        Invoke-WebRequest https://github.com/Shaquille-design/WindowsRDP/blob/main/NGROK-CHECK.bat
        Invoke-WebRequest https://github.com/Shaquille-design/WindowsRDP/blob/main/loop.bat
    - name: Make YML file for NGROK.
      run: start NGROK-AP.bat
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: sc start ngrok
    - name: Connect to your RDP 2core-7GB Ram.
      run: cmd /c NGROK-CHECK.bat
    - name: All Done! You can close Tab now! Maximum VM time:6h.
      run: cmd /c loop.bat 
